### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [AriaMinaei/pretty-error#2]
At the moment, CoffeeScript syntax errors get mildly mangled:

      Error: unexpected newline
      
      - /Users/ELLIOTTCABLE/Dropbox/Code/Paws/Paws.js/Source/additional.coffee:15:71: er
        ror: unexpected newline
      
      - @tput new (require('blessed').Tput) term: process.env['TERM']
      
      -                                                                       ^
        0m

It's not a huge deal, but it's mildly annoying to disable `pretty-error` if I need more information about a syntax error.

**Comment by ELLIOTTCABLE** [comment]
Cool! If I ever run into weird stack-trace errors with CoffeeScript again, I'll come back here with more details. <3

I'm sorry I failed as a feedback-contributor! >':

**Comment by AriaMinaei** [comment]
@ELLIOTTCABLE: not at all :) I was supposed to fix this issue a long time ago.
