### ISSUE TITLE
Add a way to disable colors

### ISSUE THREAD

**Issue by Kikobeats** [AriaMinaei/pretty-error#20]
Under production, you normally store your logs into files. if the output is colored then the result is a unreadable output line with ansi codes inside.

Could be great disable colors automatically using the env variable `process.env.NODE_END === 'production'` or add a param like `{colors: true}` in the `.render` and `.start` method or in the constructor.

Also related with #16.

**Comment by AriaMinaei** [comment]
I added this change: https://github.com/AriaMinaei/pretty-error/commit/e644d1cb340a355ae60e94c790210e839b698280. You can use it like this:
```
pe.withoutColors();
```

After that, all renders will be done without colors. Let me know if this helps, so I can bump the version.

**Comment by Kikobeats** [comment]
I like it!

**Comment by AriaMinaei** [comment]
Okay, [1.2.0](https://github.com/AriaMinaei/pretty-error/commit/31b2f6342e636e45f4a8a27d8a4ba2a52d2e383d) is out. Thanks for the suggestion :)
