### ISSUE TITLE
Typescript definition file please?

### ISSUE THREAD

**Issue by radarsu** [AriaMinaei/pretty-error#31]
Could you please make typescript definitions file for pretty-error and send em to DefinitelyTyped project?

It shouldn't be a big deal, just for consistency.
https://github.com/DefinitelyTyped/DefinitelyTyped/

**Comment by AriaMinaei** [comment]
Yes, TS definitions would be nice. You're welcome to submit a PR.

**Comment by ezintz** [comment]
Would anyone mind publishing a new version with the updated typings? Currently I got the following error while trying to compile my source:
```sh
node_modules/pretty-error/index.d.ts(4,18): error TS7010: 'start', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/pretty-error/index.d.ts(5,18): error TS7010: 'stop', which lacks return-type annotation, implicitly has an 'any' return type.
```

I had a look on the master branch where everything seems to be OK, meaning `tsc` would not exit with this error.

**Comment by AriaMinaei** [comment]
@ezintz aah looks like I forgot to publish to npm that last commit. I'll do that now :)
