### ISSUE TITLE
Edit html template?

### ISSUE THREAD

**Issue by thealjey** [AriaMinaei/pretty-error#38]
I would like to get rid of the blank lines and have each stack trace entry take only one line (with the path on the same line).
Simply changing the colors isn't enough for me, it'd be awesome if it was possible create completely custom themes, template and styles.

**Comment by aight8** [comment]
pls answer to this issue or mark this package as deprecated

**Comment by AriaMinaei** [comment]
@thealjey What you're describing is possible with the stylesheet rules and it is explained in the [docs](https://github.com/AriaMinaei/pretty-error#theming).
