### ISSUE TITLE
Render: from should not be larger than to

### ISSUE THREAD

**Issue by cggaurav** [AriaMinaei/pretty-error#40]
```
/home/travis/build/project-x/auth/node_modules/pretty-error/lib/ParsedError.js:23
      this._stack = this.error.stack;
                              ^
Error: `from` shouldn't be larger than `to`
```

This happened when I ran `render(error)` for an error that mongodb throws using their native driver while creating indexes. I could not figure out exactly what the error was but `render` was the culprit.

**Comment by halt-hammerzeit** [comment]
I'm having this too, on Travis, but not on Mac.

**Comment by cggaurav** [comment]
Yeah, I had the same on Travis.

**Comment by AriaMinaei** [comment]
Thanks guys, fix is coming :)

**Comment by AriaMinaei** [comment]
Fixed in the new version
