### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by walshie4** [AriaMinaei/pretty-error#48]
Do you have the changes to this package as they relate to version bumps documented anywhere?

**Comment by CookPete** [comment]
Very late to the party, but I've just run the repo through [`auto-changelog`](https://github.com/CookPete/auto-changelog) and got a fairly decent log: https://gist.github.com/CookPete/6a612f915bbaa0dbc05a68214b7b9006

**Comment by AriaMinaei** [comment]
Will add a changelog in the next release :)
